In [15]:
import numpy as np

In [7]:
import time

# Creating two lists with 10**7 elements each
a = list(range(1, 10**7 + 1))
b = list(range(1, 10**7 + 1))

# Measure the time taken to perform element-wise 
# multiplication using Python lists
start_time = time.time()

result_list = [a[i] * b[i] for i in range(len(a))]

end_time = time.time()
execution_time_list = end_time - start_time

print("Execution time using Python list:", execution_time_list, "seconds")

Execution time using Python list: 1.706341028213501 seconds


In [8]:
import numpy as np
import time

# Creating two NumPy arrays with 1,000,000 elements each
a = np.arange(1, 10**7 + 1)
b = np.arange(1, 10**7 + 1)

# Measure the time taken to perform 
# element-wise multiplication using  arrays
start_time = time.time()

result_array = a * b

end_time = time.time()
execution_time_array = end_time - start_time

print("Execution time using  array:",  execution_time_array, "seconds")

Execution time using  array: 0.016275405883789062 seconds


#### Creating numpy arrays

In [9]:
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(my_array)

[1 2 3 4 5]


In [11]:
my_matrix_list = [[i * j for j in range(10)] for i in range(10)]
my_mat_array = np.array(my_matrix_list)
print(my_mat_array)

[[ 0  0  0  0  0  0  0  0  0  0]
 [ 0  1  2  3  4  5  6  7  8  9]
 [ 0  2  4  6  8 10 12 14 16 18]
 [ 0  3  6  9 12 15 18 21 24 27]
 [ 0  4  8 12 16 20 24 28 32 36]
 [ 0  5 10 15 20 25 30 35 40 45]
 [ 0  6 12 18 24 30 36 42 48 54]
 [ 0  7 14 21 28 35 42 49 56 63]
 [ 0  8 16 24 32 40 48 56 64 72]
 [ 0  9 18 27 36 45 54 63 72 81]]


In [13]:
zeros_array = np.zeros(5)  # [0. 0. 0. 0. 0.]
print(zeros_array)
ones_array = np.ones((3, 2), dtype = int)  # [[1 1]
                              #  [1 1]
                              #  [1 1]]
print(ones_array)
range_array = np.arange(1, 6)  # [1 2 3 4 5]
print(range_array)
linspace_array = np.linspace(0, 1, 5)  
print(linspace_array)
# [0.   0.25 0.5  0.75 1.  ]
random_uniform = np.random.rand(3)  
print(random_uniform)
# [0.41256328 0.92475848 0.05738169]
random_normal = np.random.randn(2, 3)  
print(random_normal)
# [[-0.24573815  0.31427145 -0.57936892]
#  [ 0.6717322   1.71578591 -0.19257684]]

[0. 0. 0. 0. 0.]
[[1 1]
 [1 1]
 [1 1]]
[1 2 3 4 5]
[0.   0.25 0.5  0.75 1.  ]
[0.25012525 0.7314822  0.51421823]
[[ 0.31976334 -0.10723097  0.58844019]
 [ 1.58422701 -1.24420285  0.06430881]]


In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # (2, 3)
print(arr.dtype)  # int64
print(arr.size)   # 6

(2, 3)
int32
6


#### Universal functions in Numpy

In [16]:
# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Applying a universal function element-wise
result = np.sqrt(arr)
print(result)

[1.         1.41421356 1.73205081 2.         2.23606798]


In [17]:
# Creating two NumPy arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition using the '+' operator
result_add = arr1 + arr2
print(result_add)  # [5 7 9]

# Element-wise multiplication using the '*' operator
result_mul = arr1 * arr2
print(result_mul)  # [ 4 10 18]

[5 7 9]
[ 4 10 18]


In [18]:
arr = np.array([0, np.pi/2, np.pi])

# Trigonometric functions
result_sin = np.sin(arr)
result_cos = np.cos(arr)
result_tan = np.tan(arr)

# Exponential and logarithmic functions
result_exp = np.exp(arr)
result_log = np.log(arr)

C:\Users\timH\AppData\Local\Temp\ipykernel_27160\935950212.py:10: RuntimeWarning: divide by zero encountered in log
  result_log = np.log(arr)


#### Indexing

In [22]:
arr = np.array([10, 20, 30, 40, 50])
element = arr[2]  # Access the third element (30)
print(element)

30


In [24]:
# Slicing
arr = np.array([10, 20, 30, 40, 50])
sub_array = arr[1:4]  # Returns [20, 30, 40]
print(sub_array)

[20 30 40]


In [25]:
# fancy indexing
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 30
selected_elements = arr[mask]  # Returns [40, 50]
print(selected_elements)

[40 50]


In [27]:
# Boolean indexing
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 30
selected_elements = arr[mask]  # Returns [40, 50]
print(selected_elements)

[40 50]


In [29]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 2])
col_indices = np.array([1, 2])
selected_elements = matrix[row_indices, col_indices]  
print(selected_elements)
# Returns [2, 9]

[2 9]


In [30]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_matrix = matrix[0:2, 1:3]  
print(sub_matrix)
# Returns [[2, 3], [5, 6]]

[[2 3]
 [5 6]]


In [31]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 2])
col_indices = np.array([1, 2])
selected_elements = matrix[row_indices, col_indices]  
print(selected_elements)
# Returns [2, 9]

[2 9]


In [33]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_mask = np.array([False, True, True])
col_mask = np.array([True, False, True])
selected_elements = matrix[row_mask, col_mask]  
print(selected_elements)
# Returns [2, 7, 9]

[4 9]


In [41]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_matrix = matrix[matrix > 3]  
print(sub_matrix)
# Returns [4, 5, 6, 7, 8, 9]

[4 5 6 7 8 9]


#### Views vs copies

In [42]:
# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Creating a view of the array using slicing
view_arr = arr[1:4]

# Modifying an element in the view
view_arr[0] = 10

# The original array is also modified
print(arr)  # Output: [ 1 10  3  4  5]

[ 1 10  3  4  5]


In [45]:
# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Creating a copy of the array
copy_arr = np.copy(arr)

# Modifying an element in the copy
copy_arr[0] = 10

# The original array remains unchanged
print(arr)  # Output: [1 2 3 4 5]

[1 2 3 4 5]


In [46]:
arr = np.array([1, 2, 3, 4, 5])
view_arr = arr[1:4]
copy_arr = np.copy(arr)

print(np.may_share_memory(arr, view_arr))  # Output: True
print(np.may_share_memory(arr, copy_arr))  # Output: False

True
False


#### Sorting

In [49]:
# Creating a 1-D NumPy array
arr = np.array([4, 2, 7, 1, 5])

# Sorting the array in ascending order
sorted_arr = np.sort(arr)
print(sorted_arr)  # [1 2 4 5 7]
print(sorted_arr[::-1])

[1 2 4 5 7]
[7 5 4 2 1]


In [50]:
# Sorting the array in-place
arr.sort()
print(arr)  # [1 2 4 5 7]

[1 2 4 5 7]


In [51]:
# Creating a 2-D NumPy array
matrix = np.array([[3, 1, 4], [6, 2, 0]])

# Sorting the rows along axis 1 (columns)
sorted_rows = np.sort(matrix, axis=1)
print(sorted_rows)
# [[1 3 4]
#  [0 2 6]]

# Sorting the columns along axis 0 (rows)
sorted_cols = np.sort(matrix, axis=0)
print(sorted_cols)
# [[3 1 0]
#  [6 2 4]]

[[1 3 4]
 [0 2 6]]
[[3 1 0]
 [6 2 4]]


In [52]:
# Argsort example
arr = np.array([4, 2, 7, 1, 5])
sorted_indices = np.argsort(arr)
print(sorted_indices)  # [3 1 0 4 2]

[3 1 0 4 2]


## Attributes of numpy arrays

In [53]:
# Creating a NumPy array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Getting the shape of the array
shape = arr.shape
print(shape)  # (2, 3)

# Getting the number of dimensions (axes) of the array
dimensions = arr.ndim
print(dimensions)  # 2

(2, 3)
2


In [54]:
# Getting the data type of the array elements
data_type = arr.dtype
print(data_type)  # int64

int32


In [55]:
# Getting the total number of elements in the array
total_elements = arr.size
print(total_elements)  # 6

6


In [56]:
# Reshaping the array to (3, 2)
reshaped_arr = arr.reshape(3, 2)
print(reshaped_arr)
# [[1 2]
#  [3 4]
#  [5 6]]

[[1 2]
 [3 4]
 [5 6]]


## Playing with dimensions in NumPy

In [57]:
# Broadcasting example
a = np.array([1, 2, 3])
b = 2
result = a + b
print(result)  # Output: [3 4 5]

[3 4 5]


In [58]:
# Creating a 2-dimensional array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Broadcasting a column
column = np.array([[10], [20]])
result = array_2d + column

print(result)

Result after broadcasting:
[[11 12 13]
 [24 25 26]]


In [60]:
# Transposing a matrix
matrix = np.array([[1, 2, 3], [4, 5, 6]])
transposed_matrix1 = np.transpose(matrix)
transposed_matrix2 = matrix.T
print(transposed_matrix1)
print(transposed_matrix2)
# Output:
# [[1 4]
#  [2 5]
#  [3 6]]

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [61]:
# Reshaping an array
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = np.reshape(arr, (2, 3))
print(reshaped_arr)
# Output:
# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


#### Numpy arrays as building blocks

In [62]:
# Creating an array
arr = np.array([1, 2, 3, 4, 5, 6])

# Splitting the array into two sub-arrays
sub_arrays = np.split(arr, 2)
print(sub_arrays)  # Output: [array([1, 2, 3]), array([4, 5, 6])]

# Creating a 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Horizontally splitting the matrix into three sub-arrays
sub_arrays = np.hsplit(matrix, 3)
print(sub_arrays)
# Output: [array([[1],
#                 [4],
#                 [7]]), 
#          array([[2],
#                 [5],
#                 [8]]), 
#          array([[3],
#                 [6],
#                 [9]])]

# Vertically splitting the matrix into three sub-arrays
sub_arrays = np.vsplit(matrix, 3)
print(sub_arrays)
# Output: [array([[1, 2, 3]]), 
#          array([[4, 5, 6]]), 
#          array([[7, 8, 9]])]

[array([1, 2, 3]), array([4, 5, 6])]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [63]:
# Creating an array
arr = np.array([1, 2, 3, 4, 5, 6])

# Splitting the array into two sub-arrays
sub_arrays = np.split(arr, 2)
print(sub_arrays)  # Output: [array([1, 2, 3]), array([4, 5, 6])]

# Creating a 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Horizontally splitting the matrix into three sub-arrays
sub_arrays = np.hsplit(matrix, 3)
print(sub_arrays)
# Output: [array([[1],
#                 [4],
#                 [7]]), 
#          array([[2],
#                 [5],
#                 [8]]), 
#          array([[3],
#                 [6],
#                 [9]])]

# Vertically splitting the matrix into three sub-arrays
sub_arrays = np.vsplit(matrix, 3)
print(sub_arrays)
# Output: [array([[1, 2, 3]]), 
#          array([[4, 5, 6]]), 
#          array([[7, 8, 9]])]

[array([1, 2, 3]), array([4, 5, 6])]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [64]:
# Creating an array
arr = np.array([1, 2, 3])

# Tiling the array three times
tiled_arr = np.tile(arr, 3)
print(tiled_arr)  # Output: [1 2 3 1 2 3 1 2 3]

# Repeating each element three times
repeated_arr = np.repeat(arr, 3)
print(repeated_arr)  # Output: [1 1 1 2 2 2 3 3 3]

[1 2 3 1 2 3 1 2 3]
[1 1 1 2 2 2 3 3 3]


In [65]:
# Creating an array
arr = np.array([1, 2, 3, 4, 5])

# Deleting the element at index 2
new_arr = np.delete(arr, 2)
print(new_arr)  # Output: [1 2 4 5]

# Inserting the value 10 at index 2
new_arr = np.insert(arr, 2, 10)
print(new_arr)  # Output: [ 1  2 10  3  4  5]

[1 2 4 5]
[ 1  2 10  3  4  5]


In [66]:
# Creating an array
arr = np.array([1, 2, 3])

# Padding the array with two zeros at the beginning and end
padded_arr = np.pad(arr, (2, 2), mode='constant', constant_values=0)
print(padded_arr)  # Output: [0 0 1 2 3 0 0]

[0 0 1 2 3 0 0]
