In [ ]:
import os


In [ ]:
os.mkdir('../../evaluatiies/nieuwe_folder')

In [ ]:
os.getcwd()

In [ ]:
os.getcwd()

In [ ]:
os.path.basename('a/b/dsad/asddsdaplo/p')

In [ ]:
'a/b/dsad/asddsdaplo/p'.split('/')[-1]

In [ ]:
import numpy as np

In [ ]:
def is_prime(num):
    
    for i in range(2, int(np.sqrt(num)) + 1):
        if num % i:
            return False
    return True

In [ ]:
def generate_primes():
    
    p = 2
    yield p
    p += 1
    while True:
        if is_prime(p):
            yield p
        p += 1

In [ ]:
gen = generate_primes()

In [ ]:
for _ in range(100):
    print(next(gen))

In [ ]:
with open("Leukbestandje.txt", "r") as file:
    inhoud = file.read()
    lijnen = inhoud.split('\n')

In [ ]:
lijnen

In [ ]:
file.write("a")

In [ ]:
file.read()

In [ ]:
import json

In [ ]:
inhoud_van_json = {}
for i in range(100):
    inhoud_van_json[f"De {i}de key van mijn dictionary"] = [i ** 2, i**3, i**4]
with open("mijneerstejsonbestandje.json", "w") as huppeldepup:
    json.dump(inhoud_van_json, huppeldepup, indent = 4)

In [ ]:
inhoud_van_json

In [ ]:
with open("mijneerstejsonbestandje.json", "r") as huppeldepup:
    qwerty = json.load(huppeldepup)

In [ ]:
qwerty['1']

In [ ]:
contacts = [
    {},
    {},
    {}
]

while True:
    n = input()
    e = input()
    t = input()
    contacts.append({
        
    })

## Excel bestanden

In [ ]:
import pandas as pd
loc = 'lessenrooster_dagopleiding_data_scientist.xlsx'
df = pd.read_excel(loc)

In [ ]:
for sheet_name in xlsx.sheet_names:
    df = pd.read_excel(xlsx, sheet_name = sheet_name)
    df['Datum'] = pd.to_datetime( df.Datum, format = '%Y-%m-%d' )
    for plop, row in df.iterrows():
        print(f"Op {row['Datum'].strftime('%A')} staat Lokaal {row['Lokaal']}")

In [ ]:
a = '12\n12'
print(a)

In [ ]:
df = pd.read_excel()

In [ ]:
xlsx.to_csv("hop.tsv", sep = "\t", index = False)

In [ ]:
{
    'Sheet1' : df,
    'Sheet2' : df_over_iets_anders,
}

In [ ]:
import requests

In [ ]:
page = requests.get('https://www.zimmo.be/nl/stevoort-3512/te-koop/huis/KJKDM/?search=eyJmaWx0ZXIiOnsic3RhdHVzIjp7ImluIjpbIkZPUl9TQUxFIiwiVEFLRV9PVkVSIl19fX0%3D')

In [ ]:
requests.get??

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
soup = BeautifulSoup(page.content, "html.parser")

In [ ]:
soup.find

### Lokaal vs globaal

In [ ]:
def fun(y):
    return x * y

fun(4)

In [ ]:
globals()['x']

In [ ]:
'x' in globals()

In [ ]:
def fun2(x):
    y = 2
    return locals()

In [ ]:
plop = fun2(2)

In [ ]:
plop['q']

In [ ]:
qq = globals()

In [ ]:
type(qq)

In [ ]:
def fun():
    return locals()

In [ ]:
a = fun()

In [ ]:
a

In [ ]:
func = lambda x, y : x + y

In [ ]:
def func(x, y):
    return x + y

In [ ]:
group_to_idx = {
    'very old' : 3,
    'old' : 2,
    'young' : 1,
    'born' : 0
}

In [ ]:
lst = ['old', 'old', 'young', 'born', 'born']

In [ ]:
sorted(lst, 
           key=lambda age_group : group_to_idx[age_group],
           reverse = True)

In [ ]:
sorted?

In [ ]:
import numpy as np
def sorter(lst):
    return sorted(lst,
                     key = lambda x : (np.sin(x) + np.cos(x)) / np.tan(x))

In [ ]:
lst_sorted = sorter([1,2,3])

In [ ]:
list(map(lambda x : (np.sin(x) + np.cos(x)) / np.tan(x), lst_sorted))

In [ ]:
def func(x : int, y : int):
    """
    Dit is mijn docstring!
    """
    assert(type(x) == int)
    return x + y

In [ ]:
dit_is_een_string = """sa
dsa
sad
dsa
asd
sad
dsa
asd
sda
dsa
sda"""

In [ ]:
sorted([1,2,3], lambda x : x**2)

In [ ]:
def fun(a, key = None):
    return a

In [ ]:
print(sorted.__doc__)

In [ ]:
x = 1

In [ ]:
x.__eq__(1) # --> x == 1

In [ ]:
a = [1,2,3]
def fun(b):
    b[1] = 1000000
    return
fun(a)
print(a)

In [ ]:
a = [1, 6, 2, 3]
b = sorted(a)

In [ ]:
b = a.sort()

In [ ]:
def fun(a):
    a.sort()
    return a

In [ ]:
b = fun(a)

In [ ]:
b

In [ ]:
a =  [1, 2, [3, 4]]

In [ ]:
b = a.copy()

In [ ]:
b[-1][0] = 100

In [ ]:
a

In [ ]:
b

In [ ]:
from datetime import datetime, timedelta
a = datetime(2020, 1, 1)
b = a
b += timedelta(days = 1000)

In [ ]:
b

In [ ]:
a

In [ ]:
import pandas as pd

In [ ]:
df1 = pd.DataFrame({'1' : [1,2,3]})
df2 = pd.DataFrame({'2' : [4, 5, 6]})
lst = [df1, df2]
lst2 = lst.copy()
lst2[0].iloc[0,0] = 100
lst

In [ ]:
from copy import deepcopy
lst1 = [1, 5, 3, 2, 1, 4, [8, 3, 2, 1, 3]]
lst2 = deepcopy(lst1)
lst2[-1][-1] = 1000

In [ ]:
def 

In [ ]:
dct = {1 : [1,2,3]}
p = dct.copy()

In [ ]:
p[1][0]= 1000

In [ ]:
dct

In [ ]:
df1

In [ ]:
df3 = df1

In [ ]:
df3.iloc[0,0] = -2

In [ ]:
df1

In [3]:
import datetime

In [7]:
datum = datetime.datetime(2020, 12, 12)

In [10]:
datum.strftime("%A")

'Saturday'

In [36]:
from dataclasses import dataclass

@dataclass
class Person:
    name : str
    def __init__(self, name):
        self.name = name
        
    def __str__(self):
        return self.name

In [37]:

ddasda

In [38]:
for i in range(10):
    print(i)

Tim


In [6]:
import numpy as np
a = [1,2,3]
b = np.array(a, copy = False)
b[1] = -10
a

[1, 2, 3]

In [18]:
np.arange(0., 0.9001, 0.3)

array([0. , 0.3, 0.6, 0.9])

In [15]:
0.3 + 0.3 + 0.3 < 0.9

True

In [20]:
a = np.ones(3)
b = np.ones_like(a)

In [21]:
a

array([1., 1., 1.])

In [22]:
b

array([1., 1., 1.])

In [24]:
a = np.array([[1,2,3], [4,5,6]])
a.shape

(2, 3)

In [25]:
np.arange(0.5, 0.8, 0.1)

array([0.5, 0.6, 0.7, 0.8])

In [27]:
np.max(np.random.randint(0, 10, 10 ** 6))

9

In [29]:
import random

np.max([random.randint(0, 10) for _ in range(10 ** 6)])

10

In [41]:
a = np.arange(1, 20, dtype = float)
a[1] = np.nan
np.nanmax(a)

19.0

In [43]:
a = np.array([1, np.nan, 3])
np.nanmean(a)

2.0