## Exercise 1
Create a 2-dimensional array of shape (5, 5) with random integers between 1 and 100. Extract the diagonal elements and find their sum.

In [2]:
import numpy as np

# Create a 2-dimensional array of shape (5, 5) with random integers between 1 and 100
array = np.random.randint(1, 101, size=(5, 5))

# Extract the diagonal elements
diagonal_elements = np.diagonal(array)

# Find the sum of the diagonal elements
diagonal_sum = np.sum(diagonal_elements)

print("Array:")
print(array)
print("Diagonal elements:")
print(diagonal_elements)
print("Sum of diagonal elements:", diagonal_sum)

Array:
[[53 36 60 99  6]
 [21 56 59 49 37]
 [11 38 55 50 47]
 [98 49 85 22 41]
 [20 81 46 17 77]]
Diagonal elements:
[53 56 55 22 77]
Sum of diagonal elements: 263


## Exercise 2
Normalize the values of a $2$-dimensional array to have a mean of $0$ and a standard deviation of $1$. To normalize an array $x$, you perform the operation $\frac{x-\mu}{\sigma}$ with $\mu$ the mean and σ the standard deviation of $x$.

In [6]:
def normalize(x):
    mu = np.mean(x)
    sigma = np.mean(x)
    return (x - mu) / sigma

x = np.random.randint(1, 27, 23)
normalized_x = normalize(x)

print(x)
print(normalized_x)

[18 12 18 19  2  4  1 26 12  3 18 11 19  6 19 17  1  8 26 22  5 21 15]
[ 0.36633663 -0.08910891  0.36633663  0.44224422 -0.84818482 -0.69636964
 -0.92409241  0.97359736 -0.08910891 -0.77227723  0.36633663 -0.1650165
  0.44224422 -0.54455446  0.44224422  0.29042904 -0.92409241 -0.39273927
  0.97359736  0.669967   -0.62046205  0.59405941  0.13861386]


## Exercise 3
Create a function that takes in a $2$-dimensional array and extract rows where the sum of elements is greater than a certain threshold.

In [7]:
import numpy as np

def extract_rows_above_threshold(array, threshold):
    # Calculate the sum of elements in each row
    row_sums = np.sum(array, axis=1)
    
    # Extract rows where the sum of elements is greater than the threshold
    selected_rows = array[row_sums > threshold]
    
    return selected_rows


array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

threshold = 6

selected_rows = extract_rows_above_threshold(array, threshold)

print("Selected rows:")
print(selected_rows)

Selected rows:
[[4 5 6]
 [7 8 9]]


## Exercise 4
Compute the element-wise absolute difference between two arrays of the same shape.

In [10]:
import numpy as np

# Create two arrays of the same shape
array1 = np.random.normal(1, 2, 4)
array2 = np.random.normal(1, 2, 4)

# Compute the element-wise absolute difference
abs_diff = np.abs(array1 - array2)

print("Array 1:", array1)
print("Array 2:", array2)
print("Element-wise absolute difference:", abs_diff)

Array 1: [1.24427104 2.56008138 0.4229188  0.96912287]
Array 2: [ 5.33450644 -1.34288937  3.11215595  2.57254355]
Element-wise absolute difference: [4.09023541 3.90297075 2.68923715 1.60342068]


## Exercise 5
Calculate the cumulative sum along both rows and columns of a $2$-dimensional array.

In [12]:
matrix = np.random.randint(1, 10, (5, 5))
cumsum_rows = np.cumsum(matrix, axis = 0)
cumsum_columns = np.cumsum(matrix, axis = 1)

print(matrix)
print(cumsum_rows)
print(cumsum_columns)

[[8 8 1 8 9]
 [2 9 8 3 2]
 [7 8 4 2 4]
 [6 9 8 4 6]
 [3 6 6 4 7]]
[[ 8  8  1  8  9]
 [10 17  9 11 11]
 [17 25 13 13 15]
 [23 34 21 17 21]
 [26 40 27 21 28]]
[[ 8 16 17 25 34]
 [ 2 11 19 22 24]
 [ 7 15 19 21 25]
 [ 6 15 23 27 33]
 [ 3  9 15 19 26]]


## Exercise 6
Rescale the values of a $1$-dimensional array to lie between $0$ and $1$ using min-max scaling. Min max scaling means that we replace $x$ by $\frac{x - \min(x)}{\max(x) - \min(x)}$.

In [15]:
def min_max_scaling(x):
    min_x = np.min(x)
    max_x = np.max(x)
    return (x - min_x) / (max_x - min_x)

x = np.random.randint(1, 9, 5)
min_max_scaled_x = min_max_scaling(x)

print("Original array:")
print(x)
print("Min/max scaled version of x")
print(min_max_scaled_x)

Original array:
[3 2 3 5 1]
Min/max scaled version of x
[0.5  0.25 0.5  1.   0.  ]


## Exercise 7
Compute the matrix multiplication between a $2$-dimensional array and its transpose.

In [14]:
import numpy as np

# Create a 2-dimensional array
array = np.array([[1, 2, 3],
                  [4, 5, 6]])

# Compute the matrix multiplication between the array and its transpose
result = np.dot(array, array.T)

print("Array:")
print(array)
print("Matrix multiplication result:")
print(result)

Array:
[[1 2 3]
 [4 5 6]]
Matrix multiplication result:
[[14 32]
 [32 77]]


## Exercise 8
Replace all even numbers in an array with the negative of their value.

In [17]:
import numpy as np

# Create an array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Replace even numbers with their negative value
array[array % 2 == 0] *= -1

print("New array:")
print(array)

New array:
[ 1 -2  3 -4  5 -6  7 -8  9]


## Exercise 9
Create a $2$-dimensional array with a checkerboard pattern of $0$’s and $1$’s.

In [18]:
import numpy as np

# Define the size of the checkerboard
rows = 8
cols = 8

# Create a 2-dimensional array with a checkerboard pattern
array = np.zeros((rows, cols), dtype=int)
array[::2, ::2] = 1
array[1::2, 1::2] = 1

print("Checkerboard array:")
print(array)

Checkerboard array:
[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
