## Exercise 1
Create a 2-dimensional array of shape (5, 5) with random integers between 1 and 100. Extract the diagonal elements and find their sum.

In [2]:
import numpy as np

# Create a 2-dimensional array of shape (5, 5) with random integers between 1 and 100
array = np.random.randint(1, 101, size=(5, 5))

# Extract the diagonal elements
diagonal_elements = np.diagonal(array)

# Find the sum of the diagonal elements
diagonal_sum = np.sum(diagonal_elements)

print("Array:")
print(array)
print("Diagonal elements:")
print(diagonal_elements)
print("Sum of diagonal elements:", diagonal_sum)

Array:
[[53 36 60 99  6]
 [21 56 59 49 37]
 [11 38 55 50 47]
 [98 49 85 22 41]
 [20 81 46 17 77]]
Diagonal elements:
[53 56 55 22 77]
Sum of diagonal elements: 263


## Exercise 2
Normalize the values of a $2$-dimensional array to have a mean of $0$ and a standard deviation of $1$. To normalize an array $x$, you perform the operation $\frac{x-\mu}{\sigma}$ with $\mu$ the mean and σ the standard deviation of $x$.

In [6]:
def normalize(x):
    mu = np.mean(x)
    sigma = np.mean(x)
    return (x - mu) / sigma

x = np.random.randint(1, 27, 23)
normalized_x = normalize(x)

print(x)
print(normalized_x)

[18 12 18 19  2  4  1 26 12  3 18 11 19  6 19 17  1  8 26 22  5 21 15]
[ 0.36633663 -0.08910891  0.36633663  0.44224422 -0.84818482 -0.69636964
 -0.92409241  0.97359736 -0.08910891 -0.77227723  0.36633663 -0.1650165
  0.44224422 -0.54455446  0.44224422  0.29042904 -0.92409241 -0.39273927
  0.97359736  0.669967   -0.62046205  0.59405941  0.13861386]


## Exercise 3
Create a function that takes in a $2$-dimensional array and extract rows where the sum of elements is greater than a certain threshold.

## Exercise 4
Compute the element-wise absolute difference between two arrays of the same shape.

## Exercise 5
Calculate the cumulative sum along both rows and columns of a $2$-dimensional array.

## Exercise 6
Rescale the values of a $1$-dimensional array to lie between $0$ and $1$ using min-max scaling. Min max scaling means that we replace $x$ by $\frac{x - \min(x)}{\max(x) - \min(x)}$.

## Exercise 7
Compute the matrix multiplication between a $2$-dimensional array and its transpose.

## Exercise 8
Replace all even numbers in an array with the negative of their value.

## Exercise 9
Create a $2$-dimensional array with a checkerboard pattern of $0$’s and $1$’s.